name=Adafruit NeoPixel
version=1.15.2B
author=Adafruit
maintainer=Adafruit <adafruit@emsign.nl>
sentence=Arduino library for controlling single-wire-based LED pixels and strip.
paragraph=Arduino library for controlling single-wire-based LED pixels and strip.
category=Display
url=https://github.com/EmileSpecialProducts/Adafruit_NeoPixel
architectures=*
includes=Adafruit_NeoPixel.h
